apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresdata-clone
  namespace: production
spec:
  storageClassName: ssd
  dataSource:
    name: postgresdata-clone
    kind: PersistentVolumeClaim
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
