apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-serve
  namespace: production
spec:
  selector:
    matchLabels:
      app: api-serve
  template:
    metadata:
      labels:
        app: api-serve
    spec:
      containers:
      - name: ori-api
        image: ontola/ori_api:latest-serve
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /www/data/id
          name: api-pvc
        - mountPath: /www/data/api
          name: api-pvc
          subPath: api
        resources:
          requests:
            memory: 10Mi
      volumes:
      - name: api-pvc
        persistentVolumeClaim:
          claimName: apidata
      nodeSelector:
        cloud.google.com/gke-nodepool: persistent