apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: production
spec:
  selector:
    matchLabels:
      app: api
  replicas: 4
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: ori-api
        image: ontola/ori_api:latest
        imagePullPolicy: Always
        env:
        - name: KAFKA_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: config
              key: KAFKA_HOST
        volumeMounts:
        - mountPath: /var/lib/data/id
          name: apidata
        resources:
          requests:
            memory: 800M
            cpu: 100m
          limits:
            cpu: 500m
      volumes:
      - name: apidata
        persistentVolumeClaim:
          claimName: apidata
      nodeSelector:
        cloud.google.com/gke-nodepool: persistent