apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: production
spec:
  selector:
    matchLabels:
      app: api
  replicas: 2
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: ori-api
        image: ontola/ori_api:latest
        imagePullPolicy: Always
        env:
        - name: API_DIR
          value: /var/opt/ori_data/id/api/v1
        - name: KAFKA_HOSTNAME
          valueFrom:
            configMapKeyRef:
              key: KAFKA_HOST
              name: config
        - name: THREAD_COUNT
          value: "6"
        - name: KAFKA_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: KAFKA_HOST
              name: config
        - name: KAFKA_USERNAME
          valueFrom:
            secretKeyRef:
              key: KAFKA_USERNAME
              name: secrets
        - name: KAFKA_PASSWORD
          valueFrom:
            secretKeyRef:
              key: KAFKA_PASSWORD
              name: secrets
        - name: REDIS_ADDRESS
          value: redis://redis:6379
        - name: BUGSNAG_KEY
          value: f74b79ff1f813488777566c864845056
        volumeMounts:
        - mountPath: /var/opt/ori_data/id
          name: api-pvc
        resources:
          requests:
            memory: 350M
            cpu: 100m
          limits:
            memory: 600M
            cpu: 500m
      volumes:
      - name: api-pvc
        persistentVolumeClaim:
          claimName: api-pvc
      nodeSelector:
        cloud.google.com/gke-nodepool: persistent