apiVersion: v1
kind: Service
metadata:
  name: elastic-admin
  namespace: production
spec:
  ports:
  - port: 9200
    targetPort: 9200
  selector:
    app: elastic
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 213.127.124.245/32
  loadBalancerIP: 34.90.191.24
