apiVersion: v1
kind: Service
metadata:
  name: celery-flower
  namespace: production
spec:
  selector:
    app: flower
  type: LoadBalancer
  ports:
  - name: "http"
    port: 5555
    targetPort: 5555
