apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  name: high-priority
  namespace: production
value: 1000000
globalDefault: false
description: "High priority class for production services that can cause cascades upon failure"
