apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: production
spec:
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: postgres:11.3-alpine
        name: postgres
        # # For debugging
        # command: ["sh"]
        # stdin: true
        env:
        - name: POSTGRES_DB
          value: ori
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: secrets
              key: POSTGRES_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: POSTGRES_PASSWORD
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgresdata-clone
        # - mountPath: /var/lib/postgresql/clone
        #   name: postgresdata-clone
        resources:
          requests:
            memory: 4G
            cpu: 1
      volumes:
      - name: postgresdata-clone
        persistentVolumeClaim:
          claimName: postgresdata-clone
      # - name: postgresdata
      #   persistentVolumeClaim:
      #     claimName: postgresdata
      nodeSelector:
        cloud.google.com/gke-preemptible: "true"
