apiVersion: v1
kind: Service
metadata:
  name: postgres-admin
  namespace: production
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 213.127.124.245/32
  loadBalancerIP: 34.90.57.104
