apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresdata
  namespace: production
spec:
  storageClassName: ssd
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
