apiVersion: v1
kind: Service
metadata:
  name: search
  namespace: production
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: search
  type: LoadBalancer
  loadBalancerIP: 35.204.47.135
