FROM python:2.7

RUN mkdir -p /opt/ori
WORKDIR /opt/ori

COPY requirements.txt /opt/ori
RUN pip install --no-cache-dir -r requirements.txt

ADD . /opt/ori

# Create a virtualenv project
RUN echo 'ok'
RUN virtualenv -q /opt
RUN echo "source /opt/bin/activate; cd /opt/ori;" >> ~/.bashrc

RUN . ../bin/activate

CMD ./manage.py frontend runserver
