FROM python:3.11-alpine
MAINTAINER Joep Meindertsma <joep@argu.co>

COPY ocd_backend/requirements.txt /opt/ori/ocd_backend/requirements.txt

# Install system requirements
# Second line are used for image creation and uninstalled afterwards to reduce
# layer size. Third and fourth lines are lib dependencies and fifth line are
# package dependencies
RUN apk add --update \
  build-base git tzdata curl jq \
  libxml2-dev libxslt-dev poppler-dev jpeg-dev \
  inotify-tools libmagic nano
RUN apk add postgresql-dev gcc python3-dev musl-dev
RUN pip install --upgrade 'pip<24.3.1' \
  && pip install cython==3.0.11 \
  && pip install --no-cache-dir -r /opt/ori/ocd_backend/requirements.txt \
  && pip uninstall -y cython \
  && cp /usr/share/zoneinfo/Europe/Amsterdam /etc/localtime \
  && echo "Europe/Amsterdam" > /etc/timezone \
  && apk del build-base git tzdata
# Install backend testing dependencies
RUN pip install --no-warn-conflicts pylint==2.4.4 nose2==0.9.2 coverage==5.0.3

# Setup Celery
# Trick to redirect logs to process 1 when running multiple processes
RUN adduser -D -H celery \
  && mkdir -p /var/run/celery /opt/ori/data/static /opt/ori/data/cache /opt/ori/log \
  && ln -sf /proc/1/fd/1 /opt/ori/log/stdout

# Copy backend testing files
COPY  .pylintrc /opt/ori/.pylintrc
COPY tests/__init__.py  /opt/ori/tests/__init__.py
COPY tests/ocd_backend /opt/ori/tests/ocd_backend

# Copy all files, except for .dockerignore entries
COPY json /opt/ori/json
COPY bin /opt/ori/bin
COPY manage.py /opt/ori/manage.py
COPY es_mappings /opt/ori/es_mappings
COPY ocd_backend /opt/ori/ocd_backend
COPY version.py /opt/ori/ocd_backend/version.py
COPY version.py /opt/ori/version.py

RUN chown -R 1000:1000 /opt/ori /var/run/celery

WORKDIR /opt/ori
USER celery

ENTRYPOINT ["tail", "-f", "/dev/null"]