swagger: "2.0"
info:
  description: |
    The Open Raadsinformatie API is the place where data from dutch municipalities is made available for others to reuse.
    For more general information about the Open Raadsinformatie project see the main website: http://www.openraadsinformatie.nl/
  title: "Open Raadsinformatie API"
  version: [ ! APP VERSION HERE ! ]
  contact:
    email: "joep@argu.co"
  license:
    name: "Creative Commons Attribution 4.0"
    url: "https://creativecommons.org/licenses/by/4.0/"
host: "api.openraadsinformatie.nl"
x-google-api-name: "production"
x-google-endpoints:
- name: "api.openraadsinformatie.nl"
  allowCors: true
  target: "35.204.67.167"
consumes:
- "application/json"
produces:
- "application/json"
externalDocs:
  description: "Open Raadsinformatie Documentation"
  url: "http://docs.openraadsinformatie.nl"
tags:
- name: "Elasticsearch API"
schemes:
- "https"
- "http"
paths:
  /_cat/indices:
    get:
      tags:
        - "Elasticsearch API"
      description: |
        Elasticsearch endpoint displaying all available indices.
        See https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html for more information.
      operationId: "elastic_indices_get"
      responses:
        200:
          description: ""

  /_cat/indices/{index}:
    get:
      tags:
        - "Elasticsearch API"
      description: |
        Elasticsearch endpoint displaying the indices that match the index filter.
        See https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html for more information.
      operationId: "elastic_indices_index_get"
      parameters:
        - $ref: "#/parameters/index"
      responses:
        200:
          description: ""

  /_cat/health:
    get:
      tags:
        - "Elasticsearch API"
      description: |
        Health is a terse, one-line representation of the same information from /_cluster/health.
        See https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-health.html for more information.
      operationId: "elastic_health_get"
      responses:
        200:
          description: ""

  /_search:
    get:
      tags:
        - "Elasticsearch API"
      description: |
        Elasticsearch endpoint for searching.
        See https://elastic.co/guide/en/elasticsearch/reference/current/search-search.html for more information.
      operationId: "elastic_search_get"
      responses:
        200:
          description: ""
    post:
      tags:
        - "Elasticsearch API"
      description: |
        Elasticsearch endpoint for searching.
        See https://elastic.co/guide/en/elasticsearch/reference/current/search-search.html for more information.
      operationId: "elastic_search_post"
      responses:
        200:
          description: ""

  /_search/scroll:
    get:
      tags:
        - "Elasticsearch API"
      description: |
        Elasticsearch endpoint for scrolled searches.
        See https://elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html for more information.
      operationId: "elastic_search_scroll_get"
      parameters:
      - $ref: "#/parameters/scroll_id"
      responses:
        200:
          description: ""
    post:
      tags:
        - "Elasticsearch API"
      description: |
        Elasticsearch endpoint for scrolled searches.
        See https://elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html for more information.
      operationId: "elastic_search_scroll_post"
      parameters:
      - $ref: "#/parameters/scroll_id"
      responses:
        200:
          description: ""
    delete:
      tags:
        - "Elasticsearch API"
      description: |
        Elasticsearch endpoint to clear a scroll search context.
        See https://elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html#_clear_scroll_api for more information.
      operationId: "elastic_search_scroll_delete"
      parameters:
      - $ref: "#/parameters/scroll_id"
      responses:
        200:
          description: ""

  /_search/scroll/{scrollId}:
    get:
      tags:
      - "Elasticsearch API"
      description: |
        Elasticsearch endpoint for scrolled searches.
        See https://elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html for more information.
      operationId: "elastic_search_scrollId_get"
      parameters:
      - $ref: "#/parameters/scrollId"
      responses:
        200:
          description: ""
    post:
      tags:
      - "Elasticsearch API"
      description: |
        Elasticsearch endpoint for scrolled searches.
        See https://elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html for more information.
      operationId: "elastic_search_scrollId_post"
      parameters:
      - $ref: "#/parameters/scrollId"
      responses:
        200:
          description: ""
    delete:
      tags:
      - "Elasticsearch API"
      description: |
        Elasticsearch endpoint to clear a scroll search context.
        See https://elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html#_clear_scroll_api for more information.
      operationId: "elastic_search_scrollId_delete"
      parameters:
      - $ref: "#/parameters/scrollId"
      responses:
        200:
          description: ""

  /_msearch:
    get:
      tags:
        - "Elasticsearch API"
      description: |
        Elasticsearch endpoint for multi search.
        See https://www.elastic.co/guide/en/elasticsearch/reference/current/search-multi-search.html for more information.
      operationId: "elastic_msearch_get"
      responses:
        200:
          description: ""
    post:
      tags:
        - "Elasticsearch API"
      description: |
        Elasticsearch endpoint for multi search.
        See https://www.elastic.co/guide/en/elasticsearch/reference/current/search-multi-search.html for more information.
      operationId: "elastic_msearch_post"
      responses:
        200:
          description: ""

  /{index}/_search:
    get:
      tags:
        - "Elasticsearch API"
      description: |
        Elasticsearch endpoint for searching.
        See https://elastic.co/guide/en/elasticsearch/reference/current/search-search.html for more information.
      operationId: "elastic_search_index_get"
      parameters:
        - $ref: "#/parameters/index"
      responses:
        200:
          description: ""
    post:
      tags:
        - "Elasticsearch API"
      description: |
        Elasticsearch endpoint for searching.
        See https://elastic.co/guide/en/elasticsearch/reference/current/search-search.html for more information.
      operationId: "elastic_search_index_post"
      parameters:
        - $ref: "#/parameters/index"
      responses:
        200:
          description: ""

  /{index}/_msearch:
    get:
      tags:
        - "Elasticsearch API"
      description: |
        Elasticsearch endpoint for multi search.
        See https://www.elastic.co/guide/en/elasticsearch/reference/current/search-multi-search.html for more information.
      operationId: "elastic_msearch_index_get"
      parameters:
        - $ref: "#/parameters/index"
      responses:
        200:
          description: ""
    post:
      tags:
        - "Elasticsearch API"
      description: |
        Elasticsearch endpoint for multi search.
        See https://www.elastic.co/guide/en/elasticsearch/reference/current/search-multi-search.html for more information.
      operationId: "elastic_msearch_index_post"
      parameters:
        - $ref: "#/parameters/index"
      responses:
        200:
          description: ""

  /{index}/_doc/{docId}:
    get:
      tags:
        - "Elasticsearch API"
      description: |
        Elasticsearch endpoint for retrieving a single document.
        See https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-get.html for more information.
      operationId: "elastic_doc_index_get"
      parameters:
        - $ref: "#/parameters/index"
        - $ref: "#/parameters/docId"
      responses:
        200:
          description: ""

  /{index}/_source/{docId}:
    get:
      tags:
        - "Elasticsearch API"
      description: |
        Elasticsearch endpoint for retrieving a single document source.
        See https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-get.html for more information.
      operationId: "elastic_source_index_get"
      parameters:
        - $ref: "#/parameters/index"
        - $ref: "#/parameters/docId"
      responses:
        200:
          description: ""

  /_mapping:
    get:
      tags:
      - "Elasticsearch API"
      description: |
        Retrieves mapping definitions for indices in a cluster.
        See https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-get-mapping.html for more information.
      operationId: "elastic_mapping_get"
      responses:
        200:
          description: ""

  /{index}/_mapping:
    get:
      tags:
      - "Elasticsearch API"
      description: |
        Retrieves mapping definitions for indices in a cluster.
        See https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-get-mapping.html for more information.
      operationId: "elastic_mapping_index_get"
      parameters:
      - $ref: "#/parameters/index"
      responses:
        200:
          description: ""

parameters:
  index:
    name: "index"
    in: "path"
    description: "The Elasticsearch index to search in. For all indices use _all"
    required: true
    type: "string"
  docId:
    name: "docId"
    in: "path"
    description: "The numeric document ID to be selected"
    required: true
    type: "string"
  scrollId:
    name: "scrollId"
    in: "path"
    description: "The base64-encoded scroll ID to fetch the next batch of results from"
    required: true
    type: "string"
  scroll_id:
    name: "scroll_id"
    in: "query"
    description: "The base64-encoded scroll ID to fetch the next batch of results from"
    required: false
    type: "string"
