swagger: "2.0"
info:
  description: |
    The Open Raadsinformatie API is the place where data from dutch municipalities is made available for others to reuse.
    For more general information about the Open Raadsinformatie project see the main website: http://www.openraadsinformatie.nl/
  title: "Open Raadsinformatie API (staging)"
  version: [ ! APP VERSION HERE ! ]
  contact:
    email: "jurrian@argu.co"
  license:
    name: "Creative Commons Attribution 4.0"
    url: "https://creativecommons.org/licenses/by/4.0/"
host: "beta.openraadsinformatie.nl"
x-google-api-name: "staging"
x-google-endpoints:
- name: "beta.openraadsinformatie.nl"
  allowCors: true
  target: "35.204.67.167"
x-google-allow: "all"
security: []
securityDefinitions:
  admin_key:
    type: "apiKey"
    name: "admin_key"
    in: "header"
consumes:
- "application/json"
produces:
- "application/json"
externalDocs:
  description: "Open Raadsinformatie Documentation"
  url: "http://docs.openraadsinformatie.nl"
tags:
- name: "Elasticsearch API"
- name: "Elasticsearch API (admin)"
schemes:
- "https"
- "http"
paths:
  /elastic/{index}/_search:
    get:
      tags:
        - "Elasticsearch API"
      description: |
        Elasticsearch endpoint for searching. See https://elastic.co/guide/en/elasticsearch/reference/current/search-search.html for more information.
      operationId: "elastic_search_get"
      parameters:
        - $ref: "#/parameters/index"
      responses:
        200:
          description: ""
    post:
      tags:
       - "Elasticsearch API"
      description: |
        Elasticsearch endpoint for searching. See https://elastic.co/guide/en/elasticsearch/reference/current/search-search.html for more information.
      operationId: "elastic_search_post"
      parameters:
        - $ref: "#/parameters/index"
      responses:
        200:
          description: ""

  /elastic/{index}/_msearch:
    get:
      tags:
        - "Elasticsearch API"
      description: |
        Elasticsearch endpoint for multi search. See https://www.elastic.co/guide/en/elasticsearch/reference/current/search-multi-search.html for more information.
      operationId: "elastic_msearch_get"
      parameters:
        - $ref: "#/parameters/index"
      responses:
        200:
          description: ""
    post:
      tags:
        - "Elasticsearch API"
      description: |
        Elasticsearch endpoint for multi search. See https://www.elastic.co/guide/en/elasticsearch/reference/current/search-multi-search.html for more information.
      operationId: "elastic_msearch_post"
      parameters:
        - $ref: "#/parameters/index"
      responses:
        200:
          description: ""

  /elastic/{path}:
    get:
      tags:
        - "Elasticsearch API (admin)"
      description: |
        Elasticsearch endpoint for direct admin access of the Elasticsearch API. An api_key header is required.
      operationId: "elastic_get"
      parameters:
        - $ref: "#/parameters/path"
      responses:
        200:
          description: ""
      security:
      - admin_key: []
    post:
      tags:
        - "Elasticsearch API (admin)"
      description: |
        Elasticsearch endpoint for direct admin access of the Elasticsearch API. An api_key header is required.
      operationId: "elastic_post"
      parameters:
        - $ref: "#/parameters/path"
      responses:
        200:
          description: ""
      security:
      - admin_key: []
    put:
      tags:
        - "Elasticsearch API (admin)"
      description: |
        Elasticsearch endpoint for direct admin access of the Elasticsearch API. An api_key header is required.
      operationId: "elastic_put"
      parameters:
        - $ref: "#/parameters/path"
      responses:
        200:
          description: ""
      security:
      - admin_key: []
    delete:
      tags:
        - "Elasticsearch API (admin)"
      description: |
        Elasticsearch endpoint for direct admin access of the Elasticsearch API. An api_key header is required.
      operationId: "elastic_delete"
      parameters:
        - $ref: "#/parameters/path"
      responses:
        200:
          description: ""
      security:
      - admin_key: []

parameters:
  index:
    name: "index"
    in: "path"
    description: "The Elasticsearch index to search in. For all indices use _all"
    required: true
    type: "string"
  path:
    name: "path"
    in: "path"
    description: "The Elasticsearch path to use"
    required: true
    type: "string"
