apiVersion: v1
kind: Service
metadata:
  name: endpoints
spec:
  selector:
    app: endpoints
  type: LoadBalancer
  ports:
  - name: "http"
    port: 80
    targetPort: 80
    protocol: TCP
  - name: "https"
    port: 443
    protocol: TCP
  loadBalancerIP: {{ required "External IP needs to be set, or use 'null'" .Values.publicIp }}
