apiVersion: apps/v1
kind: Deployment
metadata:
  name: endpoints
spec:
  selector:
    matchLabels:
      app: endpoints
  template:
    metadata:
      labels:
        app: endpoints
    spec:
      containers:
      - name: endpoints
        image: gcr.io/endpoints-release/endpoints-runtime:1
        args: [
          '--http_port=80',
          '--backend=frontend:{{ required "frontendPort needs to be set" .Values.frontendPort }}',
          '--service={{ required "endpointsHost needs to be set" .Values.endpointsHost }}',
          '--rollout_strategy=managed',
        ]
        ports:
        - containerPort: 80
        - containerPort: 443
