apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
  - name: "http"
    port: {{ .Values.frontendPort }}
    targetPort: 5000
  loadBalancerIP: {{ required "External IP needs to be set, or use 'null'" .Values.publicIp }}
  loadBalancerSourceRanges:
  {{- range .Values.firewallWhitelist }}
  - {{ . }}
  {{- end }}