apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  {{- if .Values.neo4jPassword }}
  neo4j-auth: {{ cat "neo4j/" .Values.neo4jPassword | b64enc}}
  {{- else }}
  {{ $pw := randAlphaNum 32 }}
  neo4j-auth: {{ cat "neo4j/" $pw | b64enc }}
  {{- end }}
