"""renamed Source type column

Revision ID: 03547c65804e
Revises: baeeac363d3d
Create Date: 2019-07-23 17:25:15.820503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03547c65804e'
down_revision = 'baeeac363d3d'
branch_labels = None
depends_on = None


def upgrade():
    op.alter_column('source', 'type', new_column_name='entity_type')
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade():
    op.alter_column('source', 'entity_type', new_column_name='type')
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
