"""Added missing indices

Revision ID: 0a7137e18b0c
Revises: 0a8881daaac5
Create Date: 2019-09-17 14:30:03.349547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a7137e18b0c'
down_revision = '0a8881daaac5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_enricher_log_id'), 'enricher_log', ['id'], unique=False)
    op.create_index(op.f('ix_enricher_log_resource_id'), 'enricher_log', ['resource_id'], unique=False)
    op.create_index(op.f('ix_property_id'), 'property', ['id'], unique=False)
    op.create_index(op.f('ix_property_predicate'), 'property', ['predicate'], unique=False)
    op.create_index(op.f('ix_property_prop_resource'), 'property', ['prop_resource'], unique=False)
    op.create_index(op.f('ix_property_resource_id'), 'property', ['resource_id'], unique=False)
    op.create_index(op.f('ix_resource_ori_id'), 'resource', ['ori_id'], unique=False)
    op.create_index(op.f('ix_source_id'), 'source', ['id'], unique=False)
    op.create_index(op.f('ix_source_iri'), 'source', ['iri'], unique=False)
    op.create_index(op.f('ix_source_resource_ori_id'), 'source', ['resource_ori_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_resource_ori_id'), table_name='source')
    op.drop_index(op.f('ix_source_iri'), table_name='source')
    op.drop_index(op.f('ix_source_id'), table_name='source')
    op.drop_index(op.f('ix_resource_ori_id'), table_name='resource')
    op.drop_index(op.f('ix_property_resource_id'), table_name='property')
    op.drop_index(op.f('ix_property_prop_resource'), table_name='property')
    op.drop_index(op.f('ix_property_predicate'), table_name='property')
    op.drop_index(op.f('ix_property_id'), table_name='property')
    op.drop_index(op.f('ix_enricher_log_resource_id'), table_name='enricher_log')
    op.drop_index(op.f('ix_enricher_log_id'), table_name='enricher_log')
    # ### end Alembic commands ###
