"""change property order column to SmallInteger

Revision ID: 1afd444fda6b
Revises: 03547c65804e
Create Date: 2019-07-31 12:14:20.967703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1afd444fda6b'
down_revision = '03547c65804e'
branch_labels = None
depends_on = None


def upgrade():
    op.alter_column('property', 'order', type_=sa.SmallInteger)
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
