"""added more columns to source

Revision ID: 3a92325a5305
Revises: f3464eb1d467
Create Date: 2019-07-01 12:29:44.052785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a92325a5305'
down_revision = 'f3464eb1d467'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('source', sa.Column('entity', sa.String(), nullable=True))
    op.add_column('source', sa.Column('type', sa.String(), nullable=True))
    op.add_column('source', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('source', sa.Column('used_file', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source', 'used_file')
    op.drop_column('source', 'updated_at')
    op.drop_column('source', 'type')
    op.drop_column('source', 'entity')
    op.drop_column('source', 'created_at')
    # ### end Alembic commands ###
