"""empty message

Revision ID: 60dcc849b2b0
Revises: d9ee604293cf
Create Date: 2019-07-05 14:42:14.450894

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '60dcc849b2b0'
down_revision = 'd9ee604293cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property', 'prop_float')
    op.drop_column('property', 'prop_bool')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('prop_bool', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('property', sa.Column('prop_float', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
