"""first migration

Revision ID: 675fc67c8813
Revises: 
Create Date: 2019-06-24 10:04:39.331073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '675fc67c8813'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute(sa.schema.CreateSequence(sa.schema.Sequence('ori_id_seq')))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iri', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iri')
    )
    op.create_table('resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ori_id', sa.Integer(), nullable=True),
    sa.Column('iri', sa.String(), nullable=True),
    sa.Column('source_iri_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_iri_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource')
    op.drop_table('source')
    # ### end Alembic commands ###
