"""empty message

Revision ID: 88b5e802734c
Revises: 3b9423e49df5
Create Date: 2019-07-01 10:12:59.375379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88b5e802734c'
down_revision = '3b9423e49df5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('source_id', sa.Integer(), nullable=False))
    op.drop_constraint(u'resource_source_iri_id_fkey', 'resource', type_='foreignkey')
    op.create_foreign_key(None, 'resource', 'source', ['source_id'], ['id'])
    op.drop_column('resource', 'source_iri_id')
    op.add_column('source', sa.Column('resource_ori_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'source', 'resource', ['resource_ori_id'], ['ori_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'source', type_='foreignkey')
    op.drop_column('source', 'resource_ori_id')
    op.add_column('resource', sa.Column('source_iri_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'resource', type_='foreignkey')
    op.create_foreign_key(u'resource_source_iri_id_fkey', 'resource', 'source', ['source_iri_id'], ['id'])
    op.drop_column('resource', 'source_id')
    # ### end Alembic commands ###
