"""drop enricher log

Revision ID: 8d0c21474c48
Revises: 58d71214c327
Create Date: 2019-10-16 17:09:17.635593

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8d0c21474c48'
down_revision = '0a7137e18b0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_enricher_log_id', table_name='enricher_log')
    op.drop_index('ix_enricher_log_resource_id', table_name='enricher_log')
    op.drop_table('enricher_log')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enricher_log',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('resource_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('enricher_class', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('task', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], [u'resource.ori_id'], name=u'enricher_log_resource_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'enricher_log_pkey')
    )
    op.create_index('ix_enricher_log_resource_id', 'enricher_log', ['resource_id'], unique=False)
    op.create_index('ix_enricher_log_id', 'enricher_log', ['id'], unique=False)
    # ### end Alembic commands ###
