"""added order column to Property

Revision ID: b20cd816d328
Revises: c7ecdb62fa09
Create Date: 2019-07-19 17:34:03.025998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b20cd816d328'
down_revision = 'c7ecdb62fa09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property', 'order')
    # ### end Alembic commands ###
