"""add check constraint to Property

Revision ID: c7ecdb62fa09
Revises: 60dcc849b2b0
Create Date: 2019-07-11 10:21:32.671752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7ecdb62fa09'
down_revision = '60dcc849b2b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
