"""create properties table

Revision ID: c99750caba39
Revises: 675fc67c8813
Create Date: 2019-06-24 16:43:58.852887

"""
from alembic import op
import sqlalchemy as sa

import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'c99750caba39'
down_revision = '675fc67c8813'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('predicate', sa.String(), nullable=False),
    sa.Column('prop_resource', sa.Integer(), nullable=True),
    sa.Column('prop_bool', sa.Boolean(), nullable=True),
    sa.Column('prop_string', sa.String(), nullable=True),
    sa.Column('prop_text', sa.Text(), nullable=True),
    sa.Column('prop_datetime', sa.DateTime(), nullable=True),
    sa.Column('prop_integer', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['prop_resource'], ['resource.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property')
    # ### end Alembic commands ###
