"""dropped unique constraint for source iri

Revision ID: d9ee604293cf
Revises: 3a92325a5305
Create Date: 2019-07-04 16:27:17.439853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9ee604293cf'
down_revision = '3a92325a5305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'source_iri_key', 'source', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'source_iri_key', 'source', ['iri'])
    # ### end Alembic commands ###
