"""empty message

Revision ID: f3464eb1d467
Revises: 88b5e802734c
Create Date: 2019-07-01 10:31:22.411226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3464eb1d467'
down_revision = '88b5e802734c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'resource_source_id_fkey', 'resource', type_='foreignkey')
    op.drop_column('resource', 'source_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(u'resource_source_id_fkey', 'resource', 'source', ['source_id'], ['id'])
    # ### end Alembic commands ###
