name: Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
          service_account_key: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true
      - name: Kube setup
        run: ./bin/kube-setup.sh
      - name: Kube deploy
        run: ./bin/kube-deploy.sh
      - name: Bugsnag hook
        run: ./bin/bugsnag-hook.sh
